name: 'energy_project'
version: '1.0.0'
config-version: 2

profile: 'energy_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0

models:
  energy_project:
    raw:
      +materialized: view
      +schema: raw
    
    staging:
      +materialized: view
      +schema: staging
    
    dimension:
      +materialized: table
      +schema: dimension
    
    fact:
      +materialized: incremental
      +schema: fact
      +incremental_strategy: merge

    
    analytics:
      +materialized: table
      +schema: analytics
    
    analytics_special:
      cumulative:
        +materialized: incremental
        +schema: analytics
        +incremental_strategy: merge
      
      state_tracking:
        +materialized: incremental
        +schema: analytics
        +incremental_strategy: merge
