version: 2

sources:
  - name: eia_raw
    database: ENERGY_DB
    schema: RAW
    description: Raw data extracted from EIA API
    tables:
      - name: eia_hourly_demand_json
        description: >
          Raw JSON for hourly electricity demand data from EIA API for
          Duke Energy Progress East (CPLE) and Duke Energy Carolinas (DUK)
          balancing authorities in North Carolina
      - name: eia_retail_sales_json
        description: >
          Raw JSON for retail electricity sales data for North Carolina
          including sales volume, price, revenue, and customer counts
